### ISSUE TITLE
Length check of Year property throws in PostBuilder, if API returns unexpected Year length

### ISSUE THREAD

**Issue by TheUltimateC0der** [henrikfroehling/Trakt.NET#131]
You check if the lenght of the `Year` property is 4 here https://github.com/henrikfroehling/Trakt.NET/blob/3ff378047558a7d10889bfdb015f2acc16dea39b/Source/Lib/Trakt.NET/Objects/Post/Users/CustomListItems/Implementations/TraktUserCustomListItemsPostBuilder.cs#L450

My application throws exceptions because of this, But this shows https://trakt.tv/shows/chaos-communication-congress year is 19. I know this is not correct, but thats what the API reports.

**Comment by henrikfroehling** [comment]
@TheUltimateC0der Which version of Trakt.NET do you use?

**Comment by TheUltimateC0der** [comment]
I am using 1.0.0-beta

**Comment by henrikfroehling** [comment]
@TheUltimateC0der I removed the length checks for the Year property.
You can get the NuGet package here: https://www.myget.org/feed/trakt-net/package/nuget/Trakt.NET/1.0.0-beta-preview.527
