### ISSUE TITLE
Nuget over 1yr old?

### ISSUE THREAD

**Issue by bbakermmc** [henrikfroehling/Trakt.NET#144]
The nuget is over 1yr old?

![image](https://user-images.githubusercontent.com/30090055/82950725-cf86e100-9f73-11ea-8246-317bc4153c47.png)

**Comment by henrikfroehling** [comment]
@bbakermmc Yes, that's correct. I'm still working on the version 1.0.0. Plan was to release that version earlier, but that got delayed due to time issues.
You can track the progress [here](https://github.com/henrikfroehling/Trakt.NET/issues/4).
