### ISSUE TITLE
Get List Items?

### ISSUE THREAD

**Issue by bbakermmc** [henrikfroehling/Trakt.NET#145]
Is there a way to pull all the items from a list?
EX I pass a list URL and returns me back the items?
https://trakt.tv/users/bakes82/lists/netflix?sort=rank,asc

**Comment by henrikfroehling** [comment]
You can get the items from a list this way:
```csharp
TraktPagedResponse<ITraktListItem> items = await client.Users.GetCustomListItemsAsync("bakes82", "netflix");
```

Sorting ("?sort=rank,asc") isn't supported by the Trakt API yet. I checked with Postman and the parameters are ignored.
