### ISSUE TITLE
Improve interfaces for JSON objects

### ISSUE THREAD

**Issue by bakes82** [henrikfroehling/Trakt.NET#152]
Latest Nuget v1
Id expect this method to also have the nested Seasons/Episodes when I call with .SetFull no?
var data = (await traktClient.Sync.GetWatchedShowsAsync(new TraktExtendedInfo().SetFull())).ToList();

![image](https://user-images.githubusercontent.com/3197191/83834584-9e698780-a6bc-11ea-9a90-028982f0fcf2.png)

**Comment by bakes82** [comment]
My bad apparently its late and I didnt notice watchedseasons node :(

**Comment by henrikfroehling** [comment]
@bakes82
I take this as an improvement request for the interface.

Btw: Version 1.0.0 got a final release this week. You can get it via NuGet.

**Comment by bakes82** [comment]
Idk what youre improving but sure, My issue was resolved once I realized there was a watchedseasons node.  Yes Im on the v1 non pre release version.

**Comment by henrikfroehling** [comment]
Won't fix.
