### ISSUE TITLE
Need some guidance...

### ISSUE THREAD

**Issue by fullphat** [henrikfroehling/Trakt.NET#156]
I did try the Gitter Chat, but trying here too.

I'm new to this library and have a few queries...

1.  How do I tell how many pages of results have been returned and how do I move through various pages of results

1. How do I replicate either the Trakt website's dashboard or 'progress' pages?
thanks 👍

**Comment by henrikfroehling** [comment]
Hi @fullphat, thanks for using this library.

1. If you've set up the client like for example in the README and do a request like getting the trending shows, you can get the number of pages and total items and navigate through the pages like this:

```csharp
var extendedInfo = new TraktExtendedInfo() { Full = true };
var pagedParameters = new TraktPagedParameters(1, 10); // page = 1, items per page = 10
TraktPagedResponse<ITraktTrendingShow> trendingShowsResponse = await client.Shows.GetTrendingShowsAsync(extendedInfo , pagedParameters);

var totalPageCount = trendingShowsResponse.PageCount;
var totalItemCount = trendingShowsResponse.ItemCount;
var currentPage = trendingShowsResponse.Page;
var itemsPerCurrentPage = trendingShowsResponse.Limit;

// getting the next page
pagedParameters.Page = pagedParameters.Page + 1;
trendingShowsResponse = await client.Shows.GetTrendingShowsAsync(extendedInfo, pagedParameters);
```

2.
```csharp
// watched progress sorted by most recent watched item
TraktPagedResponse<ITraktHistoryItem> watchedHistoryResponse = await client.Users.GetWatchedHistoryAsync("username", pagedParameters: new TraktPagedParameters(1, 10));

// watched progress sorted by most play count
TraktListResponse<ITraktWatchedMovie> watchedMoviesResponse = await client.Users.GetWatchedMoviesAsync("username");
TraktListResponse<ITraktWatchedShow> watchedShowsResponse = await client.Users.GetWatchedShowsAsync("username");

// upcoming schedule
TraktListResponse<ITraktCalendarShow> userShowsResponse = await client.Calendar.GetUserShowsAsync();
TraktListResponse<ITraktCalendarShow> userNewShowsResponse = await client.Calendar.GetUserNewShowsAsync();
TraktListResponse<ITraktCalendarShow> userSeasonPremieresResponse = await client.Calendar.GetUserSeasonPremieresAsync();
TraktListResponse<ITraktCalendarMovie> userMoviesResponse = await client.Calendar.GetUserMoviesAsync();

// up next to watch
TraktResponse<ITraktShowWatchedProgress> showWatchedProgressResponse = await client.Shows.GetShowWatchedProgressAsync("show-id");
// showWatchedProgressResponse.Value contains properties for next episode and last episode

// alternatively you can call this to get the next episode for a show
TraktResponse<ITraktEpisode> nextEpisodeResponse = await client.Shows.GetShowNextEpisodeAsync("show-id");
```

**Comment by fullphat** [comment]
Thank you!  Will give it a try.

Awesome job by the way! 😊

**Comment by henrikfroehling** [comment]
@fullphat I'm glad I could help. Let me know if you need further guidance.

**Comment by fullphat** [comment]
Sorry for the delay replying.  I tried the above and it's not quite giving me what I want.  When I go to Trakt, I can see all the shows I'm currently watching with the most recent episode available.

Is there a way to just get the shows I'm watching, which will keep the returned list short, or is there a way to get the next available episode for all shows I'm watching?

Thanks!

**Comment by fullphat** [comment]
I need some more help 😬 

I'm really struggling with the asynchronous nature of this library, but this might be because I'm more used to using CompletionHandlers than async/await.

What I'm doing is:

- Getting the users watched shows using sync->getWatched()
- For each show, I think kick off a GetSeasonProgress()

This is great as it gives me pretty much what I need.  However, I only want to display active shows (that is, where there is a NextEpisode) in a UITableView.

My problem is that, because all the calls to GetSeasonProgress are happening asynchronously, trying to Insert rows into the UITableView is impossible as it causes a race condition which eventually generates an exception.

I can't "prepopulate" the UITableView after getWatched() has completed, as that includes ALL shows, even those with no next episode.

Help!

**Comment by henrikfroehling** [comment]
@fullphat You should consider to get familar with the async-await concepts. For starters I can recommend this documentation: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

1.
> Getting the users watched shows using sync->getWatched()

`var watchedShows = await client.Sync.GetWatchedShowsAsync(new TraktExtendedInfo() { NoSeasons = true });` returns all watched shows without the season data. This saves about 90% in response data.

2. filter the list

3.
> For each show, I think kick off a GetSeasonProgress()

`var showProgress = await client.Shows.GetWatchedProgressAsync("show-id")` to get the watched progress for each show including next episode and / or last episode.

4. Create a task list to get all watched progresses

```csharp
var tasks = new List<Task<TraktResponse<ITraktShowWatchedProgress>>>();

foreach (ITraktWatchedShow watchedShow in watchedShows)
{
    // save the task in a list
    Task<TraktResponse<ITraktShowWatchedProgress>> task = client.Shows.GetWatchedProgressAsync(watchedShow.Ids.Slug);
    tasks.Add(task);
}

// execute all tasks asynchronously
TraktResponse<ITraktShowWatchedProgress>[] shows = await Task.WhenAll(tasks).ConfigureAwait(false);
var showsList = shows.ToList();
```

**Comment by fullphat** [comment]
Thanks for the help!  I'll read up more on async/await.
