### ISSUE TITLE
Automatically retrieve the PIN and convert to Access Token

### ISSUE THREAD

**Issue by fullphat** [henrikfroehling/Trakt.NET#164]
I'm using OAUTH on iOS and I get to the Trakt.tv page with the PIN.  There's no way to copy this using the UI, but is there a way to retrieve it programmatically so I can swap it for an Access Token?

Thanks!

**Comment by henrikfroehling** [comment]
@fullphat I would recommend the device authentication process. It's basically OAuth, but simpler in usage.
You can have a look in this example on how it works: https://github.com/henrikfroehling/Trakt.NET-Examples/blob/develop/Source/Trakt.NET-Examples/Authentication/TraktDeviceAuthenticationExample/DeviceAuthentication.cs

**Comment by fullphat** [comment]
Isn't this effectively the same, except the user has to type a PIN into a website rather than enter a PIN into the app?

As it is, using an embedded Safari browser works well, it's just that the whole process could be that bit slicker if there was a way to retrieve the PIN programmatically.

**Comment by henrikfroehling** [comment]
@fullphat With `client.Authentication.CreateAuthorizationUrl()` you'll create an URL like this "https://trakt.tv/oauth/authorize?response_type=code&client_id=YOUR_CLIENT_ID&redirect_uri=urn:ietf:wg:oauth:2.0:oob".
If this URL is called, it redirects per default to this URL "https://trakt.tv/oauth/authorize/native?code=77a90a51". As you can see, there is the code as a GET parameter.

**Comment by fullphat** [comment]
Ah!  So can I capture that with this library?

**Comment by henrikfroehling** [comment]
> Ah! So can I capture that with this library?

No, it's not part of this library. But I might consider adding this feature in any future release.

**Comment by henrikfroehling** [comment]
It's very different on which platform this library is used and therefore which technology is used to show the authentication webpage. This means, it's not clear how to retrieve the code from the response, because it depends on the used technology.
The conclusion is to leave this as it is.
