### ISSUE TITLE
User requests failing

### ISSUE THREAD

**Issue by fullphat** [henrikfroehling/Trakt.NET#165]
This was previously working, but now doesn't seem to be:

```
                    TraktListResponse<ITraktCollectionShow> shows = await mClient.Users.GetCollectionShowsAsync("me");
                    foreach (ITraktCollectionShow show in shows )
                        Console.Write($"Show");
```

Simply does nothing.  It doesn't fail and `shows` definitely has something in it.  I just get no output at all.

Other `User.` methods have the same problem.

**Comment by henrikfroehling** [comment]
@fullphat What caused this issue?

**Comment by fullphat** [comment]
I had used `console.write()` rather than `console.writeline()` so the output wasn't being flushed to the console 🙄 😊
