### ISSUE TITLE
Adding GuestStars as ExtendedInfo when calling GetEpisodePeopleAsync does not return the guest starts

### ISSUE THREAD

**Issue by mpfc75** [henrikfroehling/Trakt.NET#184]
Postman Get  https://api.trakt.tv/shows/perry-mason-2020/seasons/1/episodes/8/people/?extended=guest_stars  returns many (36?) guest stars. However, the following code does not return any guest stars:

        private static async Task BugReport(string mySource, string myShow, uint mySeason = 0, uint myEpisode = 0)
        {
            TraktResponse<ITraktCastAndCrew> myPeopleEpisode;
            TraktExtendedInfo myExtendedInfo = new TraktExtendedInfo();

            myExtendedInfo.SetGuestStars();

            mySource = "episode";
            myShow = "perry-mason-2020";
            mySeason = 1;
            myEpisode = 8;

            myPeopleEpisode = await client.Episodes.GetEpisodePeopleAsync(myShow, mySeason, myEpisode, myExtendedInfo);
            if (myPeopleEpisode)
            {
                foreach (ITraktCastMember item in myPeopleEpisode.Value.Cast)
                {
                    Console.WriteLine(item.Character + " is played by " + item.Person.Name);
                }
            }
        }

Occurs in Trakt.Net version 1.0.2 under Windows 10 Visual Studio Community 2019 version 16.7.2

**Comment by skyfrk** [comment]
I just looked into this and I think that `ShowCastAndCrewObjectJsonReader.cs` and `CastAndCrewObjectJsonReader.cs` just ignore the `guest_stars` property from the response.

Example response:

```json
{
  "cast": [
    {...}
  ],
  "guest_stars": [
    {
      "character": "Hamilton Burger",
      "characters": [
        "Hamilton Burger"
      ],
      "person": {
        "name": "Justin Kirk",
        "ids": {
          "trakt": 416379,
          "slug": "justin-kirk",
          "imdb": "nm0005095",
          "tmdb": 20301,
          "tvrage": 31922
        }
      }
    }
  ],
  "crew": {...}
}

```

`CastAndCrewObjectJsonReader` excerpt:

```csharp
switch (propertyName)
{
    case JsonProperties.PROPERTY_NAME_CAST:
        traktCastAndCrew.Cast = await castReader.ReadArrayAsync(jsonReader, cancellationToken);
        break;
    case JsonProperties.PROPERTY_NAME_CREW:
        traktCastAndCrew.Crew = await crewReader.ReadObjectAsync(jsonReader, cancellationToken);
        break;
    default:
        await JsonReaderHelper.ReadAndIgnoreInvalidContentAsync(jsonReader, cancellationToken);
        break;
}
```

`ShowCastAndCrewObjectJsonReader` excerpt:

```csharp
switch (propertyName)
{
    case JsonProperties.PROPERTY_NAME_CAST:
        traktShowCastAndCrew.Cast = await showCastReader.ReadArrayAsync(jsonReader, cancellationToken);
        break;
    case JsonProperties.PROPERTY_NAME_CREW:
        traktShowCastAndCrew.Crew = await showCrewReader.ReadObjectAsync(jsonReader, cancellationToken);
        break;
    default:
        await JsonReaderHelper.ReadAndIgnoreInvalidContentAsync(jsonReader, cancellationToken);
        break;
}
```

I want to fix this issue. Should I add a new property to `ITraktCastAndCrew` and `ITraktShowCastAndCrew` or should I add the guest stars to the `IEnumerable<ITraktCastMember> Cast`?

**Comment by henrikfroehling** [comment]
@skyfrk
Yes, that's correct. The property "guest_stars" is currently ignored for `ITraktShowCastAndCrew`.
`ITraktShowCastAndCrew` needs the property `IEnumerable<ITraktShowCastMember> GuestStars`.

**Comment by skyfrk** [comment]
Only `ITraktShowCastAndCrew` needs the property? What about `ITraktCastAndCrew`?

**Comment by henrikfroehling** [comment]
> Only `ITraktShowCastAndCrew` needs the property? What about `ITraktCastAndCrew`?

`ITraktCastAndCrew` is used for movie people and general people requests, which don't have guest stars.
For people requests it doesn't make sense and for movie people requests I just checked in postman and there are no guest stars returned.

If you want, you can also add the property in `ITraktCastAndCrew`.
But the future goal is to somehow merge `ITraktCastAndCrew` and `ITraktShowCastAndCrew`. The only difference between these interfaces is the property `EpisodeCount`.
