### ISSUE TITLE
GetShowAsync returns Status null when status is 'upcoming'

### ISSUE THREAD

**Issue by mpfc75** [henrikfroehling/Trakt.NET#208]
Calls to GetShowAsync (v1.1.0) returns status=null for shows in Trakt with a status of 'upcoming' (for example your-honor-us  or  the-surgeon-s-cut). 

Postman shows 'upcoming' for both of the show examples above.

**Comment by henrikfroehling** [comment]
Missing value for "upcoming" in `TraktShowStatus`.

**Comment by henrikfroehling** [comment]
Created an issue for missing documentation: https://github.com/trakt/api-help/issues/235
