### ISSUE TITLE
Calendar methods do not accept a value greater than 31 for days

### ISSUE THREAD

**Issue by mpfc75** [henrikfroehling/Trakt.NET#220]
The Trakt `calendars/my/shows/start_date/days` API allows for days <= 33. Trakt.Net GetUserShowsAsync throws error if days>31. 

` System.ArgumentOutOfRangeException
  Message=days must have a value between 1 and 31
Parameter name: Days`

I believe Trakt has recently increased this limit from 31.

Postman call `api.trakt.tv/calendars/my/shows/2021-03-01/33` returns shows from 2021-03-01 to 2021-04-02. 

FYI, changing the days in Postman to a larger number (e.g., 100) will result in a status code 200 but the data returned still ends at 2021-04-02 (33 days).

The above is also true of `calendars/all/shows/new/start_date/days` and GetAllNewShowsAsync.

Occurs in Trakt.Net v1.1.0

**Comment by henrikfroehling** [comment]
@mpfc75 
I looked at the [documentation](https://trakt.docs.apiary.io/#reference/calendars/get-new-shows). It says the maximum is 33 days. But since higher values also return a successful status code, I might consider removing this check completely.
