### ISSUE TITLE
GetShowAsync returns Status null when status is 'planned'

### ISSUE THREAD

**Issue by mpfc75** [henrikfroehling/Trakt.NET#221]
This is a variation of issue "GetShowAsync returns Status null when status is 'upcoming' #208".

Calls to GetShowAsync (v1.1.0) returns status=null for shows in Trakt with a status of 'planned' (for example home-economics).

Postman shows 'planned' for the show home-economics.

(It seems Trakt isn't keeping their documentation current with the API. So far, we have seen undocumented status of upcoming and planned. I wonder if there are more?)

**Comment by henrikfroehling** [comment]
@mpfc75 
Good catch. I already created an [issue](https://github.com/trakt/api-help/issues/235) if there are more values missing in the documentation.

I might consider a bugfix release for version 1.1.0 in the next couple of days.

**Comment by mpfc75** [comment]
Yes, I did see your issue with Trakt but I also see that they haven't replied yet.  It occurred to me that with their move away from TVDB to using TMDB exclusively that TMDB may be the source of the 'bad data'.  I checked the show there and sure enough the status is "Planned" (capital P).  But reviewing the TMDB Contribution Bible [https://www.themoviedb.org/bible/tv](url) upcoming and planned are not listed as valid. So I don't know how it is getting thru.

**Comment by henrikfroehling** [comment]
I don't know what's exactly wrong with the data or not, but I added the value to the status so it gets accepted in future versions.

**Comment by henrikfroehling** [comment]
@mpfc75 A new version 1.1.1 is on Nuget.

**Comment by mpfc75** [comment]
@henrikfroehling  Thanks Henrik! v1.1.1 seems to resolve the three issues I reported (at least the calendar days and status=planned. I don't have a show at the moment that has a status=upcoming but I'm confident it will work too).
