### ISSUE TITLE
post builder feature: add support for posting collected episodes without ids 

### ISSUE THREAD

**Issue by aspik** [henrikfroehling/Trakt.NET#30]
as discussed on gitter, here is the request for adding support to post collected episodes without IDs, but only IDs on the show object. The episode object should also have the collectedAt attribute. 
Attached a valid JSON with an example body.
[post_collected_episodes_no_ids.zip](https://github.com/henrikfroehling/Trakt.NET/files/2217376/post_collected_episodes_no_ids.zip)

Endpoint:
https://api.trakt.tv/sync/collection

**Comment by henrikfroehling** [comment]
This issue has the follow-up issue #35.
