### ISSUE TITLE
post builder feature: add support for posting watched episodes without ids

### ISSUE THREAD

**Issue by aspik** [henrikfroehling/Trakt.NET#31]
as discussed on gitter, here is the request for adding support to post watched episodes without IDs, but only IDs on the show object. The episode object should also have the watchedAt attribute. 
Attached a valid JSON with an example body:
[post_watched_episodes_no_ids.zip](https://github.com/henrikfroehling/Trakt.NET/files/2217385/post_watched_episodes_no_ids.zip)

Endpoint:
https://api.trakt.tv/sync/history

**Comment by henrikfroehling** [comment]
@aspik This scenario should work as aspected. The `ITraktSyncHistoryPost` can hold a collection of `ITraktSyncHistoryPostShow`, which can each hold a collection of `ITraktSyncHistoryPostShowSeason` which can each hold a collection of `ITraktSyncHistoryPostShowEpisode`. `ITraktSyncHistoryPostShow`, `ITraktSyncHistoryPostShowSeason` and `ITraktSyncHistoryPostShowEpisode` already have a property `WatchedAt`.

To build a `ITraktSyncHistoryPost`, use the `TraktSyncHistoryPostBuilder`. For this case you can use the `AddShow(ITraktShow show, PostHistorySeasons seasons)` or the `AddShow(ITraktShow show, DateTime watchedAt, PostHistorySeasons seasons)`method.

`PostHistorySeasons` is a collection of `PostHistorySeason` and `PostHistorySeason` is a collection of `PostHistoryEpisode`.

Example:
```csharp
var postHistorySeasons = new PostHistorySeasons
{
    1, // season number
    { 2 }, // season number
    { 3, DateTime.Now }, // season number, season watchedAt
    { 4, new PostHistoryEpisodes { 1 } }, // season number, { episode number }
    { 5, DateTime.Now, new PostHistoryEpisodes { 2 } }, // season number, season watchedAt, { episode number }
    { 6, new PostHistoryEpisodes { 1, 2, 3 } }, // season number, { multiple episode numbers }
    { 7, DateTime.Now, new PostHistoryEpisodes { 1, 2, 3 } }, // season number, season watchedAt { multiple episode numbers }
    { 8, new PostHistoryEpisodes // season number
         {
             { 1, DateTime.Now } // episode number, episode watchedAt
         }
    },
    { 9, DateTime.Now, new PostHistoryEpisodes // season number, season watchedAt
         {
             { 2, DateTime.Now } // episode number, episode watchedAt
         }
    }
    },
    { 10, new PostHistoryEpisodes // season number
         {
             { 1, DateTime.Now }, // episode number, episode watchedAt
             2,
             { 3, DateTime.Now } // episode number, episode watchedAt
         }
    },
    { 11, DateTime.Now, new PostHistoryEpisodes // season number, season watchedAt
         {
             { 2, DateTime.Now  }, // episode number, episode watchedAt
             { 3 }, // episode number
             4 // episode number
         }
    },
};
```
`PostHistorySeasons` and `PostHistoryEpisodes` each also have an `Add(...)` method for their collection items with several overloads.
