### ISSUE TITLE
[Bug]: GetWatchedHistoryAsync() by imdb id

### ISSUE THREAD

**Issue by michalss** [henrikfroehling/Trakt.NET#348]
### Failure description?

During the GetWatchedHistoryAsync i cannot use id of imdb, which is allowed but not documented in api. Can you please change that id type from uint to string or object ?

Here is a proof:

![image](https://user-images.githubusercontent.com/1000729/198067327-fba14ec9-77ce-44e7-8a29-1fa237e46e1c.png)

### Version

1.2.0 (Latest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by henrikfroehling** [comment]
@michalss I'll fix it for version 1.3.0, which will be the next release.

**Comment by henrikfroehling** [comment]
@michalss As seen in the answer in https://github.com/trakt/api-help/discussions/378#discussioncomment-3971681 the only supported ID is the Trakt ID.
