### ISSUE TITLE
[Bug]: Does not work with MAUI Android Target

### ISSUE THREAD

**Issue by michalss** [henrikfroehling/Trakt.NET#351]
### Feature description

Im working on the project where i would like to use Trakt.Net as dynamic loaded lib. But i cannot load it on Android getting error

![image](https://user-images.githubusercontent.com/1000729/199601910-03457a04-cad0-4f51-87e9-608a44465de0.png)

Not sure how this issue can be handled but it simple does not work. It does work with WinUI3, but not on Android.

Regards

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by henrikfroehling** [comment]
.NET Standard should be [compatible](https://stackoverflow.com/a/69300690/6622539) with .NET Maui, but I'm not 100% sure on that.
I, for myself, haven't tried building apps with .NET Maui yet.
Maybe, this could be related to this issue https://github.com/dotnet/maui/issues/10154?

**Comment by michalss** [comment]
i will try to find some time to get sample project together. its complicated because it need to be release package and it does not woking only with android and during dynamic loading. Very tight and specific  case.

**Comment by henrikfroehling** [comment]
I created a sample [MauiApp1.zip](https://github.com/henrikfroehling/Trakt.NET/files/9933210/MauiApp1.zip) Maui app and had no issue running it as an Android app with latest stable Trakt.NET 1.2.0.

![Screenshot_1667511691](https://user-images.githubusercontent.com/3494788/199840886-1ed6a6f4-2b2c-48ee-a0e1-9eb274a4dfa3.png)

**Comment by michalss** [comment]
try to load dll dynamically.

**Comment by henrikfroehling** [comment]
The NuGet package contains a "Trakt.NET.dll".
Did you already try to load the assembly with `Assembly.LoadFrom("[path-to-dll]\\Trakt.NET.dll")`?

**Comment by michalss** [comment]
i did but neve mind. I did it other way. Attached it directly to my Main project and leave dynamical loading..
