### ISSUE TITLE
[Feature Request]: More Sample how to use this lib?

### ISSUE THREAD

**Issue by michalss** [henrikfroehling/Trakt.NET#355]
### Feature description

Hi im having very hard time to understand how use Sync actions(gets are ok but posts) for example.  I would like to add something to watchlist but i dont get what variable this function wants ??

```csharp
_client.Sync.AddWatchlistItemsAsync(????????);
```

for example how do i get ITraktSyncWatchlistPost object ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michalss** [comment]
im sorry, maybe im stupid but no matter i do i have no idea :( 

```csharp
                var getService = service.trakt.ToString() ?? service.slug;
                var watchItem = await _client.Movies.GetMovieAsync(getService, traktExtended);
                
                await _client.Sync.AddWatchlistItemsAsync(watchItem);
```

this does not work trying to understand it for an hour but still no idea how to do this :( Pls HELP @henrikfroehling  Thx

**Comment by michalss** [comment]
Sorry for spamm. Found it Here : https://github.com/henrikfroehling/Trakt.NET/discussions/218

Still think think would help to make more samples how to use TraktPost and so on.. Regards

**Comment by henrikfroehling** [comment]
> Sorry for spamm. Found it Here : https://github.com/henrikfroehling/Trakt.NET/discussions/218
> 
> Still think think would help to make more samples how to use TraktPost and so on.. Regards

Agreed.
More samples and better documentation are already on my To-do list.
