### ISSUE TITLE
Refreshing authorization not working with expired or invalid access token

### ISSUE THREAD

**Issue by aspik** [henrikfroehling/Trakt.NET#36]
It is not possible to refresh the authorization, if the client is "restarted".
old implementation:
https://github.com/henrikfroehling/TraktApiSharp/blob/master/Source/Lib/TraktApiSharp/Authentication/TraktAuthentication.cs#L376
new implementation:
https://github.com/henrikfroehling/Trakt.NET/blob/958b1c4a78b854d507d7cf2410d699e8046fa176/Source/Lib/Trakt.NET/Requests/Handler/AuthenticationRequestHandler.cs#L254

In the new version there is only a check, if the authentication is authorized. During a refresh the authentication is always not authorized, therefore it is not possible to do a refresh. Please bring back the old check :)

**Comment by aspik** [comment]
Sure:
1. start the client,
2. authorize with pin: 
https://github.com/aspik/TraktPluginMP2/blob/master/TraktPluginMP2/TraktPluginMP2/Models/TraktSetupModel.cs#L120
3. save the response to file:
https://github.com/aspik/TraktPluginMP2/blob/master/TraktPluginMP2/TraktPluginMP2/Models/TraktSetupModel.cs#L269-L274
4. close the client,
5. start the client,
6. refresh the authorization by exchanging the refresh token:
https://github.com/aspik/TraktPluginMP2/blob/master/TraktPluginMP2/TraktPluginMP2/Services/LibrarySynchronization.cs#L447-L464
https://github.com/aspik/TraktPluginMP2/blob/master/TraktPluginMP2/TraktPluginMP2/Services/TraktClientProxy.cs#L58

Result: exception with message: "not authorized" is thrown. 

I'm afraid that the stack trace will not be helpful. I'm using a wrapper around the TraktClient (for unit tests purpose ), and I can catch only the AggegateException:
https://github.com/aspik/TraktPluginMP2/blob/master/TraktPluginMP2/TraktPluginMP2/Services/TraktClientProxy.cs#L281-L294

**Comment by henrikfroehling** [comment]
@aspik I think, you didn't set the saved authorization in the client.
https://github.com/aspik/TraktPluginMP2/blob/master/TraktPluginMP2/TraktPluginMP2/Services/LibrarySynchronization.cs#L460
There might be missing this:
```csharp
_traktClient.Authorization = savedAuth;
```

See the example "Serialize and deserialize authorization information" at https://github.com/henrikfroehling/Trakt.NET#basic-usage

**Comment by aspik** [comment]
This was not needed with the old lib. And tbh I'm not sure why I have to do it? :) its only the refreshtoken which matters. 
I just restored back the old check in the new version, compiled it and exchange in my plugin. Now is all working as before :)

**Comment by henrikfroehling** [comment]
Ah, okay. You're right, that should also work with just the refresh token.
