### ISSUE TITLE
Few TVDbId doesn't recognized?

### ISSUE THREAD

**Issue by asturel** [henrikfroehling/Trakt.NET#42]
Just noticed that some show (by TVDBId) just won't added to my watch history. (The Show goes into ITraktSyncHistoryPostResponse.NotFound)
E.g.:
https://trakt.tv/shows/wynonna-earp tvdbid: 305582 https://www.thetvdb.com/series/wynonna-earp
It works fine if I provide the traktv id. Sadly even if I pass the IMDBId, GetBestId() returns the TVDBId.
Also I'm not sure if this is the library fault, but if the TVDBId is so unreliable then 'GetBestId' could be changed to prefer imdbid over tvdbid?

**Comment by asturel** [comment]
Seems like it's fixed :/ atleast 1x4-1x9 recognized.

**Comment by henrikfroehling** [comment]
@asturel

Implementation of `GetBestId()`:
```csharp
public string GetBestId()
{
    if (Trakt > 0)
        return Trakt.ToString();

    if (!string.IsNullOrEmpty(Slug))
        return Slug;

    if (Tvdb.HasValue && Tvdb.Value > 0)
        return Tvdb.Value.ToString();

    if (!string.IsNullOrEmpty(Imdb))
        return Imdb;

    if (Tmdb.HasValue && Tmdb.Value > 0)
        return Tmdb.Value.ToString();

    if (TvRage.HasValue && TvRage.Value > 0)
        return TvRage.Value.ToString();

    return string.Empty;
}
```

Sound's like it is/was an error on the server side of Trakt.tv and not an error in the library.
