### ISSUE TITLE
API Search by text query doesn't allow NullOrEmpty string

### ISSUE THREAD

**Issue by djlorent** [henrikfroehling/Trakt.NET#45]
As the title above,
Library API "Search by text query" doesn't allow a null value or empty string in searchQuery parameter;
but Trakt API allow it, and is useful, for example, to search by genre only.

Can you implement this "feature" ?

Thank You so much for all.

**Comment by henrikfroehling** [comment]
The `searchQuery` parameter is required as stated in the Trakt API documentation. See https://trakt.docs.apiary.io/#reference/search/text-query/get-text-query-results.
