### ISSUE TITLE
Bug in ratin

### ISSUE THREAD

**Issue by joggs** [henrikfroehling/Trakt.NET#46]
I have found a possible bug when using the TraktSyncRatingsPostBuilder.
If you set the rating property in the episode instance, it becomes null when performing the traktSyncRatingsPostBuilder.Build().
See example below.

` ITraktEpisode traktEpisode = new TraktEpisode();
                ITraktEpisodeIds ids = new TraktEpisodeIds();
                ids.Tvdb = Convert.ToUInt32(episodeItem.ProviderIds["Tvdb"]);                 
                traktEpisode.Ids = ids;
                traktEpisode.Rating = rating;  //Bug, ratings value is correctly entered into the property
                
                TraktSyncRatingsPostBuilder traktSyncRatingsPostBuilder = new TraktSyncRatingsPostBuilder();
                traktSyncRatingsPostBuilder.AddEpisode(traktEpisode);
                var build = traktSyncRatingsPostBuilder.Build(); //The rating value is missing from the build object.

                var addRatingResponse = await GetTraktClient().Sync.AddRatingsAsync(build);``

**Comment by henrikfroehling** [comment]
The rating in `ITraktEpisode` is the rating which you get from Trakt.tv for an episode.
If you use the builder the rating in the episode isn't used, because it represents an average rating for an episode.
So, if you want to post a rating for an episode, you can use the overloaded method `AddEpisode(ITraktEpisode episode, int rating)`:
```csharp
ITraktEpisode episode = new TraktEpisode
{
    Ids = new TraktEpisodeIds
    {
        Tvdb = 123456
    }
};

int rating = 8;

TraktSyncRatingsPostBuilder ratingsBuilder = new TraktSyncRatingsPostBuilder();
ratingsBuilder.AddEpisode(episode, rating);
ITraktSyncRatingsPost post = builder.Build();
```
