### ISSUE TITLE
Wrong type assignment for lists

### ISSUE THREAD

**Issue by TheUltimateC0der** [henrikfroehling/Trakt.NET#61]
I was implementing the **TraktClient.Users.AddCustomListItemsAsync** function as mentioned in the documentation. After debugging 3 hours at 2 in the morning, i finally downloaded the code to debug the lib also. Found out that your statement was wrong.

https://github.com/henrikfroehling/Trakt.NET/blob/87efcb7de6d738a3f7a9bf734873bc718fda4691/Source/Lib/Trakt.NET/Objects/Post/Users/CustomListItems/Implementations/TraktUserCustomListItemsPostBuilder.cs#L462

`_listItemsPost.Movies = new List<TraktUserCustomListItemsPostMovie>();` should actually be `_listItemsPost.Movies = new List<ITraktUserCustomListItemsPostMovie>();`

That is why the cast here doesnt work https://github.com/henrikfroehling/Trakt.NET/blob/87efcb7de6d738a3f7a9bf734873bc718fda4691/Source/Lib/Trakt.NET/Objects/Post/Users/CustomListItems/Implementations/TraktUserCustomListItemsPostBuilder.cs#L59 and no items get added to the list.

You already did this for the People list https://github.com/henrikfroehling/Trakt.NET/blob/87efcb7de6d738a3f7a9bf734873bc718fda4691/Source/Lib/Trakt.NET/Objects/Post/Users/CustomListItems/Implementations/TraktUserCustomListItemsPostBuilder.cs#L474

TraktApiSharp: 1.0.0-alpha3

**Comment by henrikfroehling** [comment]
@TheUltimateC0der Hi, can you please provide a simple example on how to reproduce this behavior and also stack trace?

**Comment by henrikfroehling** [comment]
Resolves with https://github.com/henrikfroehling/Trakt.NET/commit/d2567428ff79d728ea0ce94db9f991694cbe565e
