### ISSUE TITLE
[Feature Request]: Add support for "shows/updates" endpoint

### ISSUE THREAD

**Issue by eliottrobson** [henrikfroehling/Trakt.NET#620]
### Feature description

Trakt API exposes an endpoint to "Get recently updated shows"
https://trakt.docs.apiary.io/#reference/shows/updates/get-recently-updated-shows

It would be good to include a request to handle this in the API

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by henrikfroehling** [comment]
Already existing in Version 1.3.0.
https://github.com/henrikfroehling/Trakt.NET/blob/release-1.3.0/Source/Lib/Trakt.NET/Modules/TraktShowsModule.cs#L905
