### ISSUE TITLE
[Feature Request]: Add support for "movies/updates" endpoint

### ISSUE THREAD

**Issue by eliottrobson** [henrikfroehling/Trakt.NET#621]
### Feature description

Trakt API exposes an endpoint to "Get recently updated movies"
https://trakt.docs.apiary.io/#reference/movies/updates/get-recently-updated-movies

It would be good to include a request to handle this in the API

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by henrikfroehling** [comment]
Already existing in Version 1.3.0.
https://github.com/henrikfroehling/Trakt.NET/blob/release-1.3.0/Source/Lib/Trakt.NET/Modules/TraktMoviesModule.cs#L762

**Comment by eliottrobson** [comment]
Apologies! I was searching for the method by API / URL naming not by action. Thank you for your help :D
