### ISSUE TITLE
Exception when search text query is empty

### ISSUE THREAD

**Issue by TheUltimateC0der** [henrikfroehling/Trakt.NET#64]
The implementation of the API allows the `query` parameter to be an empty string. However you implemented a check for if `query` is `string.empty` and throw an exception if assertion is true.

https://github.com/henrikfroehling/Trakt.NET/blob/87efcb7de6d738a3f7a9bf734873bc718fda4691/Source/Lib/Trakt.NET/Requests/Search/SearchTextQueryRequest.cs#L51

Reference: https://trakt.docs.apiary.io/#reference/search/text-query/get-text-query-results

**Comment by henrikfroehling** [comment]
In this issue, only the empty string bug will be fixed.
Missing filter support will be fixed in issue https://github.com/henrikfroehling/Trakt.NET/issues/72 .

**Comment by TheUltimateC0der** [comment]
if this issue is done, would you mind releasing a new package to nuget ?

**Comment by henrikfroehling** [comment]
Resolved with commit https://github.com/henrikfroehling/Trakt.NET/commit/2ded58e8c9c18c5d17a484f35ffb49c879eb42da

@TheUltimateC0der I won't release a new package until all 1.0.0-beta release issues are resolved.
But you can get the deployment items (including NuGet package) here: https://dev.azure.com/henrikfroehling/Trakt.NET/_build/results?buildId=151&view=results
Deployment items are always built as if it were a release version.

Alternatively, you can add the MyGet-NuGet feed https://www.myget.org/F/trakt-net/api/v3/index.json to always get the latest CI/CD packages (just look for preview packages - preferably with the highest build number).
