### ISSUE TITLE
Invalid implementation for Networks / List / Get networks

### ISSUE THREAD

**Issue by TheUltimateC0der** [henrikfroehling/Trakt.NET#65]
The property name has to be `Name` not `Network`
https://github.com/henrikfroehling/Trakt.NET/blob/87efcb7de6d738a3f7a9bf734873bc718fda4691/Source/Lib/Trakt.NET/Objects/Basic/ITraktNetwork.cs#L5

Reference: https://trakt.docs.apiary.io/#reference/networks/list/get-networks

**Comment by TheUltimateC0der** [comment]
The property Network is also `null` for all Objects in the list

**Comment by henrikfroehling** [comment]
@TheUltimateC0der Does this work now with the following NuGet package: https://dev.azure.com/henrikfroehling/_apis/resources/Containers/6809329?itemPath=Trakt.NET.145-DeploymentItems%2FTrakt.NET.1.0.0-preview.145.nupkg ?

**Comment by TheUltimateC0der** [comment]
I can confirm it works
